/**
 * @file src/texts.ts
 * @description All PT-BR UI strings for the Ajuda Ai application.
 */

export const texts: Record<string, any> = {
    pt: {
        common: {
            loading: "Carregando…",
            error: "Ocorreu um erro",
            retry: "Tentar novamente",
            save: "Salvar",
            cancel: "Cancelar",
            delete: "Excluir",
            confirm: "Confirmar",
            close: "Fechar",
            quotaExceeded: "Sua cota do Gemini acabou. Verifique seu plano e faturamento no Google AI Studio.",
            highDemand: "O modelo está com alta demanda. Tentando novamente...",
            seeMore: "Ver mais",
            seeLess: "Ver menos",
        },
        onboarding: {
            title: "Bem-vindo ao Ajuda Ai! 🎓",
            message: "O Ajuda Ai é o seu assistente inteligente para estudos e provas. Para começar, você precisa de uma chave de API do Google Gemini.",
            aiStudioInfo: "Se você não está usando o Google AI Studio, precisará criar sua própria chave de API (é grátis!).",
            getApiKey: "Pegar minha API Key",
            goToSettings: "Ir para Configurações",
            gotIt: "Entendi!",
        },
        security: {
            warningTitle: "Aviso de Segurança e Privacidade",
            warningMessage: "Sua chave de API é salva localmente no seu navegador. Nunca envie informações sensíveis ou dados pessoais nos anexos das provas.",
        },
        home: {
            title: "Ajuda Ai",
            subtitle: "Suas provas",
            newTest: "Nova Prova",
            emptyState: "Nenhuma prova ainda. Crie uma!",
            lastSession: "Última sessão",
            testNamePlaceholder: "Nome da prova (ex: Matemática, História)",
            createTest: "Criar Prova",
            deleteTestTitle: "Excluir prova permanentemente?",
            deleteTestDesc: "Isso excluirá permanentemente a prova",
            deleteTestWarning: "e todos os seus dados. Esta ação não pode ser desfeita.",
        },
        test: {
            tabs: {
                warm: "Preparação",
                questions: "Prova",
            },
            warm: {
                title: "Preparar IA",
                uploadHint: "Envie materiais para a IA estudar (PDF, Imagens, Áudio, YouTube)",
                analyzing: "Estudando…",
                done: "Contexto salvo!",
                summaryTitle: "Resumo da Preparação",
                keyConcepts: "Conceitos Chave",
                formulas: "Fórmulas",
                vocabulary: "Vocabulário",
                predictedTypes: "Tipos de Questões Previstos",
                reRun: "Refazer Preparação",
                addMore: "Adicionar mais material",
                noMaterial: "Nenhum material de preparação adicionado.",
                preparationMode: "Modo de Preparação",
                generateImage: "Gerar Imagem de Apoio",
                tokenCost: "Custo de Tokens Estimado:",
                tokenCostLevels: {
                    low: "Baixo (<= 50k)",
                    medium: "Médio (<= 100k)",
                    high: "Alto (<= 150k)",
                    veryHigh: "Muito Alto (>= 200k)",
                },
                addedFiles: "Arquivos Adicionados:",
                visualSummary: "Infográfico / Resumo Visual",
                visualSummaryAlt: "Infográfico",
            },
            questions: {
                upload: "Upload de Questões",
                generating: "Gerando...",
                checking: "Verificando...",
                generateBtn: "Gerar Respostas",
                takePhoto: "Tirar Foto",
                addedQuestions: "Questões Adicionadas:",
                dropzone: "Arraste e solte arquivos aqui, ou clique para selecionar",
                structured: "Modo Estruturado",
                creative: "Modo Criativo",
                checked: "Verificado ✓",
                noQuestions: "Nenhuma questão enviada.",
                resolutionMode: "Modo de Resolução",
                correctOption: "Opção Correta",
                explanation: "Explicação",
                shortAnswer: "Resposta Curta",
                detailedAnswer: "Resposta Detalhada",
                finalAnswer: "Resposta Final",
                solutionSteps: "Passo a Passo",
                asciiArt: "Representação Visual",
                camera: {
                    title: "Câmera",
                    error: "Não foi possível acessar a câmera. Verifique as permissões.",
                    photosCount: "{count} foto(s)",
                    done: "Concluir ({count})",
                },
            },
            answers: {
                title: "Respostas",
                summary: "Resumo das Respostas",
                generatedDraw: "Desenho gerado",
                questionLabel: "Questão",
                generatingImage: "Gerando imagem…",
                generatedVisualAlt: "Visual gerado",
                questionPrefix: "Q",
                unsupportedFormat: "Formato de resposta não suportado.",
                modifiedForSafety: "Modificada por segurança/direitos autorais",
            },
            header: {
                history: "Histórico",
                createdAt: "Criado em",
            },
            prepared: "Preparado",
            notPrepared: "Sem preparação",
            card: {
                preparedTooltip: "Contexto de preparação disponível",
            },
        },
        settings: {
            title: "Configurações",
            general: "Geral",
            apiKey: "Chave de API do Gemini",
            language: "Idioma",
            languageOptions: {
                pt: "Português",
                en: "English",
            },
            model: "Modelo de texto",
            modelOptions: {
                pro: "Gemini 3.1 Pro (Recomendado)",
                flash: "Gemini 3.1 Flash (Rápido)",
                flashOld: "Gemini 3 Flash (Rápido)",
            },
            imageModel: "Modelo de imagem",
            imageModelOptions: {
                flash: "Gemini 3.1 Flash Image (Padrão)",
                pro: "Gemini 3 Pro Image (Alta Qualidade)",
            },
            defaultMode: "Modo padrão",
            modeOptions: {
                structured: "Modo Estruturado (Direto)",
                creative: "Modo Criativo (Raciocínio Livre)",
            },
            preparationMode: "Modo de Preparação",
            preparationModeOptions: {
                summarize: "Resumir (Padrão)",
                full_attachments: "Enviar Anexos Completos",
            },
            enableImageGeneration: "Permitir Geração de Imagens",
            enableImageGenerationDesc: "Se desativado, a IA não tentará gerar nenhuma imagem (útil se a API não suportar).",
            generateImageInPreparation: "Gerar Imagem/Infográfico na Preparação",
            enableModelDowngrade: "Downgrade Automático de Modelo",
            enableModelDowngradeDesc: "Se a cota do modelo atual exceder, tenta modelos mais baratos automaticamente.",
            thinkingBudget: "Orçamento de Pensamento (Tokens)",
            stealth: "Modo Furtivo",
            vibration: "Vibração",
            saveSuccess: "Configurações salvas com sucesso!",
            recitationHandling: "Prevenção de Filtro de Citação",
            recitationDesc: "Estratégia usada quando a IA bloqueia a resposta por direitos autorais.",
            recitationParaphrase: "Parafrasear (Padrão)",
            recitationToken: "Injeção de Tokens (Experimental)",
            pwa: "Aplicativo (PWA)",
            installApp: "Instalar Aplicativo",
            installAppDesc: "Instale o Ajuda Ai na sua tela inicial para acesso rápido e discreto.",
            alreadyInstalled: "Aplicativo já instalado ou não suportado.",
        },
        stealth: {
            enable: "Modo Furtivo",
            blackout: "Tela Preta",
            incomingCall: "Chamada de",
            accept: "Aceitar",
            decline: "Recusar",
        },
        history: {
            title: "Histórico de Sessões",
            empty: "Nenhuma sessão encontrada para esta prova.",
            sessionDate: "Data",
            sessionMode: "Modo",
            questionsCount: "Questões",
            backToTest: "Voltar para a Prova",
            noAnswers: "Nenhuma resposta encontrada.",
            deleteSessionTitle: "Excluir sessão?",
            deleteSessionDesc: "Isso excluirá permanentemente esta sessão e todas as suas respostas. Esta ação não pode ser desfeita.",
            status: {
                completed: "Concluído",
                error: "Erro",
                in_progress: "Em Progresso",
            },
        },
    },
    en: {
        common: {
            loading: "Loading…",
            error: "An error occurred",
            retry: "Try again",
            save: "Save",
            cancel: "Cancel",
            delete: "Delete",
            confirm: "Confirm",
            close: "Close",
            quotaExceeded: "Your Gemini quota has run out. Check your plan and billing in Google AI Studio.",
            highDemand: "Model is under high demand. Retrying...",
            seeMore: "See more",
            seeLess: "See less",
        },
        onboarding: {
            title: "Welcome to Ajuda Ai! 🎓",
            message: "Ajuda Ai is your intelligent assistant for studies and exams. To get started, you need a Google Gemini API key.",
            aiStudioInfo: "If you are not using Google AI Studio, you will need to create your own API key (it's free!).",
            getApiKey: "Get my API Key",
            goToSettings: "Go to Settings",
            gotIt: "Got it!",
        },
        security: {
            warningTitle: "Security and Privacy Warning",
            warningMessage: "Your API key is saved locally in your browser. Never upload sensitive information or personal data in test attachments.",
        },
        home: {
            title: "Help Ai",
            subtitle: "Your Tests",
            newTest: "New Test",
            emptyState: "No tests yet. Create one!",
            lastSession: "Last session",
            testNamePlaceholder: "Test name (e.g.: Math, History)",
            createTest: "Create Test",
            deleteTestTitle: "Delete test permanently?",
            deleteTestDesc: "This will permanently delete the test",
            deleteTestWarning: "and all of its data. This action cannot be undone.",
        },
        test: {
            tabs: {
                warm: "Preparation",
                questions: "Test",
            },
            warm: {
                title: "Prepare AI",
                uploadHint: "Upload materials for AI to study (PDF, Images, Audio, YouTube)",
                analyzing: "Studying…",
                done: "Context saved!",
                summaryTitle: "Preparation Summary",
                keyConcepts: "Key Concepts",
                formulas: "Formulas",
                vocabulary: "Vocabulary",
                predictedTypes: "Predicted Question Types",
                reRun: "Redo Preparation",
                addMore: "Add more material",
                noMaterial: "No preparation material added.",
                preparationMode: "Preparation Mode",
                generateImage: "Generate Support Image",
                tokenCost: "Estimated Token Cost:",
                tokenCostLevels: {
                    low: "Low (<= 50k)",
                    medium: "Medium (<= 100k)",
                    high: "High (<= 150k)",
                    veryHigh: "Very High (>= 200k)",
                },
                addedFiles: "Added Files:",
                visualSummary: "Infographic / Visual Summary",
                visualSummaryAlt: "Infographic",
            },
            questions: {
                upload: "Question Upload",
                generating: "Generating...",
                checking: "Checking...",
                generateBtn: "Generate Answers",
                takePhoto: "Take Photo",
                addedQuestions: "Added Questions:",
                dropzone: "Drag and drop files here, or click to select",
                structured: "Structured Mode",
                creative: "Creative Mode",
                checked: "Verified ✓",
                noQuestions: "No questions uploaded.",
                resolutionMode: "Resolution Mode",
                correctOption: "Correct Option",
                explanation: "Explanation",
                shortAnswer: "Short Answer",
                detailedAnswer: "Detailed Answer",
                finalAnswer: "Final Answer",
                solutionSteps: "Step by Step",
                asciiArt: "Visual Representation",
                camera: {
                    title: "Camera",
                    error: "Could not access the camera. Please check permissions.",
                    photosCount: "{count} photo(s)",
                    done: "Done ({count})",
                },
            },
            answers: {
                title: "Answers",
                summary: "Answers Summary",
                generatedDraw: "Generated drawing",
                questionLabel: "Question",
                generatingImage: "Generating image…",
                generatedVisualAlt: "Generated visual",
                questionPrefix: "Q",
                unsupportedFormat: "Unsupported answer format.",
                modifiedForSafety: "Modified for safety/copyright",
            },
            header: {
                history: "History",
                createdAt: "Created at",
            },
            prepared: "Prepared",
            notPrepared: "No preparation",
            card: {
                preparedTooltip: "Preparation context available",
            },
        },
        settings: {
            title: "Settings",
            general: "General",
            apiKey: "Gemini API Key",
            language: "Language",
            languageOptions: {
                pt: "Portuguese",
                en: "English",
            },
            model: "Text model",
            modelOptions: {
                pro: "Gemini 3.1 Pro (Recommended)",
                flash: "Gemini 3.1 Flash (Fast)",
                flashOld: "Gemini 3 Flash (Fast)",
            },
            imageModel: "Image model",
            imageModelOptions: {
                flash: "Gemini 3.1 Flash Image (Default)",
                pro: "Gemini 3 Pro Image (High Quality)",
            },
            defaultMode: "Default mode",
            modeOptions: {
                structured: "Structured Mode (Direct)",
                creative: "Creative Mode (Free Reasoning)",
            },
            preparationMode: "Preparation Mode",
            preparationModeOptions: {
                summarize: "Summarize (Default)",
                full_attachments: "Send Full Attachments",
            },
            enableImageGeneration: "Enable Image Generation",
            enableImageGenerationDesc: "If disabled, the AI will not attempt to generate any images (useful if the API does not support it).",
            generateImageInPreparation: "Generate Image/Infographic in Preparation",
            enableModelDowngrade: "Automatic Model Downgrade",
            enableModelDowngradeDesc: "If the current model quota is exceeded, automatically try cheaper models.",
            thinkingBudget: "Thinking Budget (Tokens)",
            stealth: "Stealth Mode",
            vibration: "Vibration",
            saveSuccess: "Settings saved successfully!",
            recitationHandling: "Citation Filter Prevention",
            recitationDesc: "Strategy used when AI blocks the response due to copyright.",
            recitationParaphrase: "Paraphrase (Default)",
            recitationToken: "Token Injection (Experimental)",
            pwa: "Application (PWA)",
            installApp: "Install Application",
            installAppDesc: "Install Ajuda Ai on your home screen for fast and discreet access.",
            alreadyInstalled: "Application already installed or not supported.",
        },
        stealth: {
            enable: "Stealth Mode",
            blackout: "Blackout Screen",
            incomingCall: "Incoming call from",
            accept: "Accept",
            decline: "Decline",
        },
        history: {
            title: "Session History",
            empty: "No sessions found for this test.",
            sessionDate: "Date",
            sessionMode: "Mode",
            questionsCount: "Questions",
            backToTest: "Back to Test",
            noAnswers: "No answers found.",
            deleteSessionTitle: "Delete session?",
            deleteSessionDesc: "This will permanently delete this session and all its answers. This action cannot be undone.",
            status: {
                completed: "Completed",
                error: "Error",
                in_progress: "In Progress",
            },
        },
    },
};
